<TextInputWidget>:
    canvas:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            pos: self.pos
            size: self.size

    TextInput:
        text: 'c0c.ink'
        multiline: False
        pos: 400, 380
        allow_copy: False

    TextInput:
        text: 'cocpy.com'
        pos: 100, 180
        halign: 'center'
        background_color: 100, 2, 2, 1

    TextInput:
        text: 'first'
        pos: 400, 180
        readonly: True
