# 自定义布局
<YushiruiWidget>:

    # 垂直布局
    orientation: 'vertical'

    # 复选框，有组就是单选框
    CheckBox:
        # 组
        group: '复选框组'
        # id
        id: first_check_0
        # 颜色
        color: .6, .2, .2, 1

    # 复选框
    CheckBox:
        # 组
        group: '复选框组'
        # 颜色
        color: .2, .6, .2, 1

    # 复选框
    CheckBox:
        # 组
        group: '复选框组'
        # 颜色
        color: .2, .2, .6, 1

    # 复选框
    CheckBox:
        # 颜色
        color: .6, .6, .6, 1
