<YushiruiWidget>:

    anim_kwargs: {'d': 10, 't': 'linear'}
    page: 2
    border: '100dp'
    swipe_threshold: .8

    Button:
        text: 'Page0'
        background_color: 0.3, .3, .3, 1

    Button:
        text: 'Page1'
        background_color: 0.9, .3, .3, 1

    Button:
        text: 'Page2'
        background_color: 0.3, .9, .3, 1

    Button:
        text: 'Page3'
        background_color: 0.3, .3, .9, 1
