<YushiruiWidget>:


    # 画布
    canvas:
        # 颜色
		Color:
			rgba: [1, 1, 1, 1]
		# 矩形
		Rectangle:
			size: self.size
			pos: self.pos

    Button:
        text: 'yushirui'
        size_hint: .2, .15

        # 窗口相对位置，按钮的中间，到窗口左边0.3，按钮的顶边，到窗口底边0.6
        pos_hint: {'center_x': 0.3, 'top': 0.75}

    Button:
        text: 'xueyu'
        size_hint: .2, .15

        # 窗口相对位置，按钮左上角，与窗口左边0.6，下边0.25
        pos_hint: {'x': 0.6, 'y': .25}
