<YushiruiWidget>:
    padding: 20
    spacing: 20
    cols: 3
    col_force_default: True
    col_default_width: 120
    row_force_default: True
    row_default_height: 40

    cols_minimum: {0:130, 1:140}


    canvas:
		Color:
			rgba: [1, 1, 1, 1]
		Rectangle:
			size: self.size
			pos: self.pos

    Button:
        text: 'First'
        size_hint_x: None
        width: '100px'

    Button:
        text: 'Second'

    Button:
        text: 'Third'

    Button:
        text: 'Fourth'
