<YushiruiWidget>:

    # 翻页动画、持续时间
    anim_kwargs: {'d': 10, 't': 'linear'}
    # 默认页码
    page: 2
    # 边界
    border: '100dp'
    # 翻页灵敏度
    swipe_threshold: .8

    Button:
        text: 'Page0'
        background_color: 0.3, .3, .3, 1

    Button:
        text: 'Page1'
        background_color: 0.9, .3, .3, 1

    Button:
        text: 'Page2'
        background_color: 0.3, .9, .3, 1

    Button:
        text: 'Page3'
        background_color: 0.3, .3, .9, 1
