# 自定义布局
<YushiruiWidget>:

    size_hint: .5, .2
    pos_hint: {'center_x': .5, 'center_y': .5}

    # 气泡
    Bubble:

        # 气泡按钮
        BubbleButton:
            # 文本
            text: 'Bubble'

        # 气泡按钮
        BubbleButton:
            # 文本
            text: 'Button'
            # 默认背景色清空
            background_normal: ''
            # 背景色
            background_color: .1, .5, .5, 1
            # 点击事件
            on_release: print('yushirui click')
